### ISSUE TITLE
No app icon for some apps (maybe exclusive issue to uwp apps)

### ISSUE THREAD

**Issue by Sukuratchi** [hdlx/MacAppSwitcher#1]
Hi there! Found a slight bug.

Seems like no app icon shows for uwp apps/apps installed with a "non native" window border (idk how to explain it)

For example if I open arc (web browser), I don't get the arc icon as the thumbnail when doing alt tab. Same thing happens with the microsoft store while quickly testing this

https://github.com/hdlx/MacAppSwitcher/assets/66184829/f6133f6e-feea-4b7d-9410-ae5a4170b66b

Example of issue shown above^^

https://github.com/hdlx/MacAppSwitcher/assets/66184829/e5438f84-06f0-4fa3-b1e8-fb7523fa0cab

Icons do appear when doing win+tab (shown above) and regular alt tab

**Comment by hdlx** [comment]
Hi!
Indeed, it seems that I need to handle UWP apps as a specific case, I started to look at it, I will tackle this when I have some time soon.
Thanks for the feedback ! :-)

**Comment by Sukuratchi** [comment]
Thank you for your hard work!
Tested MS Store and the calculator app, those do indeed work as intended
Arc browser still has the same behavior (no icon, just the default "placeholder" one)

![image](https://github.com/hdlx/MacAppSwitcher/assets/66184829/8f917c5a-b129-47ae-b261-9b511fb006f8)

**Comment by hdlx** [comment]
Should be good this time, at least for arc.
