### ISSUE TITLE
Darkmode

### ISSUE THREAD

**Issue by senegg** [hdlx/MacAppSwitcher#10]
darkmode would be nice :)
Thanks for your work.

**Comment by hdlx** [comment]
Added dark mode to last release 🙂 
In config file, it can bet set to "auto" (default setting, matches windows theme), "light", or "dark". Regen config file (launch the exe without any config file next to it) for an exemple.

**Comment by hdlx** [comment]
Yes, it's a bit random with every new release since it's a machine learning detection, it might get better with time.
Similar issue: https://github.com/hdlx/MacAppSwitcher/issues/8
