### ISSUE TITLE
Windows terminal icon doesn't show properly

### ISSUE THREAD

**Issue by mcrampon** [hdlx/MacAppSwitcher#13]
![image](https://github.com/user-attachments/assets/a2a1e89f-d300-4f1b-93f9-b44796d689c5)

Not sure what happened. Used to work in previous versions.

It's supposed to look like this: 
![image](https://github.com/user-attachments/assets/0a3612f2-3bd5-470e-bcd6-884146af8963)

**Comment by hdlx** [comment]
Indeed, thanks for the feedback, this is fixed in last version :-)
