### ISSUE TITLE
Request - Mouse Selection in Tab Window

### ISSUE THREAD

**Issue by fadingsignal** [hdlx/MacAppSwitcher#4]
Great app, thank you so much!

I had a request. When hitting alt+tab, it would be amazing if you could click on any of the icons rather than having to tab tab tab across them. Sometimes what I need is at the end.

If you don't have donations set up already you should :)

**Comment by hdlx** [comment]
Hey, tanks for your feedback! Mouse support would be nice indeed, I'll find some time to add it.

Until now I didn't feel the app was robust enough to set up donations, but I will consider!

**Comment by mcrampon** [comment]
Would be nice indeed. May I suggest having an option to disable it as well? In the config file? :pray:

**Comment by hdlx** [comment]
I added mouse support :-) Enabled by default, but can be turned off by setting "allow mouse: false" in the config file. Regen config file for an example.
