### ISSUE TITLE
libwinpthread-1.dll missing

### ISSUE THREAD

**Issue by be9em0t** [hdlx/MacAppSwitcher#7]
![fDhQXhDR3h](https://github.com/user-attachments/assets/4ec2c5da-7caa-47f7-a343-c2e51de7d5b0)
Windows 11

**Comment by hdlx** [comment]
Indeed, there is a dependency to this dll, which I didn't notice since it's present on my system. The following version should fix it, can you confirm? Thanks! https://github.com/hdlx/MacAppSwitcher/releases/tag/v0.9

**Comment by mcrampon** [comment]
Seems to be fixed
