### ISSUE TITLE
Detected as trojan

### ISSUE THREAD

**Issue by mcrampon** [hdlx/MacAppSwitcher#8]
Windows Defender is a bit annoying with that. Got that message when downloading MAS 0.9.
I think I was on 0.3 before and didn't have the issue

![image](https://github.com/user-attachments/assets/ed00d411-c820-4df4-b6e0-4165b6159261)

I ran Microsoft Safety Scanner just to confirm this was a false positive indeed 🤡

**Comment by hdlx** [comment]
Yes 😞  "ml" in "Wacatac.B!ml" stands for machine learning, so it's hard to know why some executable do trigger this and some don't. There is a similar issue: https://github.com/hdlx/MacAppSwitcher/issues/6 . It's indeed a false positive. I sent an exe to Microsoft. I uploaded many .exe recently, so the user count per executable is low. Having more user might help.

**Comment by mcrampon** [comment]
Noted. Closing this then, as it's a duplicate
