### ISSUE TITLE
Bug: Can only move 1 item BW/FW

### ISSUE THREAD

**Issue by mcrampon** [hdlx/MacAppSwitcher#9]
Using MAS 0.9, I can only move one item forward or 1 item backward when using the app switcher. Subsequent TAB presses don't do anything 😢

**Comment by hdlx** [comment]
Hey! Sorry to hear this. I can't repro but I reworked a lot of the internal logic, for the better I hope, please test the latest release.

**Comment by mcrampon** [comment]
I have a slightly different issue on 0.10: Now the problem is that the previous app immediately jumps to the second position. So every time I press TAB, I end up on the second to last app I came from.

Essentially I'm stuck between two apps.

**Comment by hdlx** [comment]
Right, you're using tab for both switch keys, but with different hold keys. I can repro, will fix :)

**Comment by hdlx** [comment]
Please retry 0.10, I updated the .exe 🙂

**Comment by mcrampon** [comment]
Works like a charm, thanks <3
